name: example_map_release

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  make_release:
    name: example_map_release
    runs-on: [self-hosted, windows, x64]

    steps:
      - uses: actions/checkout@v6

      - name: Install uv with caching enabled
        uses: astral-sh/setup-uv@v7
        with:
          enable-cache: true

      - name: Install the project with all dev dependencies
        run: uv sync --locked --all-extras --dev

      - name: Install tempo-cli
        run: uv tool install git+https://www.github.com/Tempo-Organization/tempo-cli

      - name: Run tempo-cli mod release creation command
        run: tempo_cli run full_run_all --settings_json ".tempo.json"

      - name: List all releases
        run: dir Modding/releases /b /a-d *.zip > release_list.txt

      - name: Temporary body.md creation
        run: echo temporary placeholder > body.md

      # - name: Release
      #   uses: softprops/action-gh-release@v2
      #   with:
      #     body_path: "body.md"
      #     tag_name: ${{ steps.extract_version.outputs.version }}
      #     files: |
      #       Modding/releases/*.zip
      #   env:
      #     GITHUB_TOKEN: ${{ secrets.PERSONAL_ACCESS_TOKEN }}



# then print the contents of current_dir/.tempo.json

# have a step here that checks the json file mods info, to get mod names, mod version, description, etc...

# have a step here that makes a release for each using the information above

# add mod version
# add mod description
# add way to increment specific mod versions through commitizen logic
