name: generate_mod_releases

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  generate_mod_releases:
    name: generate_mod_releases
    runs-on: [self-hosted, windows, x64]

    steps:
      - name: Checkout
        uses: actions/checkout@v6

      - name: Generate mod releases using action-tempo-cli-release
        uses: Tempo-Organization/action-tempo-cli-release@v1.4
